services:
  postgres:
    image: postgres:16-alpine
    container_name: medicpadi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medicpadi_internal
    restart: always

  redis:
    image: redis:7-alpine
    container_name: medicpadi-redis
    ports:
      - "6379:6379"
    networks:
      - medicpadi_internal
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data

  # Gateway Management Service
  gateway-service:
    image: colauncha/medicpadi-gateway:main
    container_name: medicpadi-gateway
    ports:
      - "3010:3000"
    depends_on:
      - postgres
    env_file:
      - ./apps/gateway/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  # Auth Service
  auth-service:
    image: colauncha/medicpadi-auth:main
    container_name: medicpadi-auth
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/auth/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  # Profile Service
  profile-service:
    image: colauncha/medicpadi-profile:main
    container_name: medicpadi-profile
    depends_on:
      - postgres
    env_file:
      - ./apps/profile/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  # Notification Service
  notification-service:
    image: colauncha/medicpadi-notification:main
    container_name: medicpadi-notification
    depends_on:
      - postgres
    env_file:
      - ./apps/notification/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  services-service:
    image: colauncha/medicpadi-services:main
    container_name: medicpadi-services
    depends_on:
      - postgres
    env_file:
      - ./apps/services/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  orders-service:
    image: colauncha/medicpadi-orders:main
    container_name: medicpadi-orders
    depends_on:
      - postgres
    env_file:
      - ./apps/orders/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  ehr-service:
    image: colauncha/medicpadi-ehr:main
    container_name: medicpadi-ehr
    depends_on:
      - postgres
    env_file:
      - ./apps/ehr/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  transactions-service:
    image: colauncha/medicpadi-transactions:main
    container_name: medicpadi-transactions
    depends_on:
      - postgres
    env_file:
      - ./apps/transactions/.env.staging
    networks:
      - medicpadi_internal
    restart: always

  # community-service:
  #   image: colauncha/medicpadi-community:main
  #   container_name: medicpadi-community
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./apps/community/.env.staging
  #   networks:
  #     - medicpadi_internal
  #   restart: always

networks:
  medicpadi_internal:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
