services:
  postgres:
    image: postgres:16-alpine
    container_name: medicpadi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medicpadi_internal
    restart: no

  redis:
    image: redis:7-alpine
    container_name: medicpadi-redis
    ports:
      - "6380:6379"
    networks:
      - medicpadi_internal
    restart: no
    volumes:
      - redis_data:/var/lib/redis/data

  # Gateway Management Service
  gateway-service:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    # image: colauncha/medicpadi-gateway:main
    container_name: medicpadi-gateway
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/gateway/.env.staging
    restart: no

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    # image: colauncha/medicpadi-auth:main
    container_name: medicpadi-auth
    networks:
      - medicpadi_internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/auth/.env.staging
    restart: no

  # Profile Services
  profile-service:
    build:
      context: .
      dockerfile: ./apps/profile/Dockerfile
    # image: colauncha/medicpadi-profile:main
    container_name: medicpadi-profile
    networks:
      - medicpadi_internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/profile/.env.staging
    restart: no
  
  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
    # image: colauncha/medicpadi-notification:main
    container_name: medicpadi-notification
    networks:
      - medicpadi_internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/notification/.env.staging
    restart: no

  services-service:
    build:
      context: .
      dockerfile: ./apps/services/Dockerfile
    # image: colauncha/medicpadi-services:main
    container_name: medicpadi-services
    networks:
      - medicpadi_internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/services/.env.staging
    restart: no

  orders-service:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
    # image: colauncha/medicpadi-orders:main
    container_name: medicpadi-orders
    networks:
      - medicpadi_internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/orders/.env.staging
    restart: no

  ehr-service:
    build:
      context: .
      dockerfile: ./apps/ehr/Dockerfile
    # image: colauncha/medicpadi-ehr:main
    container_name: medicpadi-ehr
    networks:
      - medicpadi_internal
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/ehr/.env.staging
    ports:
      - "3006:3006"
    restart: no

  transactions-service:
    build:
      context: .
      dockerfile: ./apps/transactions/Dockerfile
    # image: colauncha/medicpadi-transactions:main
    container_name: medicpadi-transactions
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/transactions/.env.staging
    networks:
      - medicpadi_internal
    restart: no

  # AI Agent Service
  ai-agent-service:
    build:
      context: .
      dockerfile: ./apps/ai-agent/Dockerfile
    # image: colauncha/medicpadi-ai-agent:main
    container_name: medicpadi-ai-agent
    networks:
      - medicpadi_internal
    env_file:
      - ./apps/ai-agent/.env.staging
    restart: no

networks:
  medicpadi_internal:
    driver: bridge

volumes:
  postgres_data:
  redis_data: