autoInstallPeers: true

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  es5-ext: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  unrs-resolver: true
  '@scarf/scarf': false

# packageExtensions:
#   '@nestjs-modules/mailer':
#     exports:
#       '.':
#         require: ./index.js
#         import: ./index.js
#       './dist/adapters/handlebars.adapter':
#         require: ./dist/adapters/handlebars.adapter.js
#         import: ./dist/adapters/handlebars.adapter.js
#       './dist/adapters/ejs.adapter':
#         require: ./dist/adapters/ejs.adapter.js
#         import: ./dist/adapters/ejs.adapter.js
#       './dist/adapters/pug.adapter':
#         require: ./dist/adapters/pug.adapter.js
#         import: ./dist/adapters/pug.adapter.js